### ISSUE TITLE
Sort order of related content sidebar

### ISSUE THREAD

**Issue by hklish01** [katebron/notthischarter#10]
http://moongoosedesigns.com/customizing-post-sort-order-using-the-category-posts-widget/

Change to asc.

**Comment by katebron** [comment]
I assumed we were already using this plugin, but i don't see it anywhere.

**Comment by hklish01** [comment]
This is just a widget.



Heather Klish | Systems Librarian
TTS : Library Technology Services
Tufts University
heather.klish@tufts.edu
617.627.5853

-------- Original message --------

**Comment by katebron** [comment]
The problem is, i can't find the file the change: 

_To change this order, you need to edit the cat-posts.php file in the category-posts plugin directory in the plugins directory._

**Comment by hklish01** [comment]
Damn.  Didn't see that.  Let me look into this.



Heather Klish | Systems Librarian
TTS : Library Technology Services
Tufts University
heather.klish@tufts.edu
617.627.5853


-------- Original message --------

**Comment by hklish01** [comment]
Here's the correct plugin:

https://keesiemeijer.wordpress.com/related-posts-by-taxonomy/templates/

This can be one of the last things to do . . .

**Comment by hklish01** [comment]
Trying to maybe figure this out for you.  Give them a try and see what happens.

Use this example in your (child) theme’s functions.php file.

add_filter( 'related_posts_by_taxonomy_widget_args', 'my_widget_filter' );
function my_widget_filter( $args, $instance ) {
    $args['order'] = 'ASC';
    return $args;
}

Or maybe this?

add_filter( 'related_posts_by_taxonomy_widget_args', 'my_widget_filter' );
function my_widget_filter( $args, $instance ) {
    $defaults['order'] = 'ASC';
    return $args;
}

**Comment by hklish01** [comment]
I think I found another way to do this if we can't do it this way.

**Comment by katebron** [comment]
OK. Can you describe what/where the sorting you want is so i can see if the above works locally?

**Comment by hklish01** [comment]
I want to sort them by ASC.  Right now they’re sorted DESC.

Heather
. . . . . . . . . . . . . . . . . . . . . . . . . . . .
Heather Klish | Systems Librarian
TTS : Library Technology Services
Tufts University
heather.klish@tufts.edu<mailto:heather.klish@tufts.edu> | 617.627.5853

**Comment by katebron** [comment]
Sorry to be daft here, but _which_ posts do you mean? The ones on the front page in the main area, or the sidebar, or both?

**Comment by katebron** [comment]
Ok makes sense now, thank you

**Comment by katebron** [comment]
hallelujah: https://wordpress.org/support/topic/sort-posts-alphabetically-3/

**Comment by hklish01** [comment]
That's great!
