### ISSUE TITLE
Background of title/photo bar

### ISSUE THREAD

**Issue by hklish01** [katebron/notthischarter#13]
I removed the color of the title bar from the inline styles.  Can you make it 

#dbe6ec (which is the top color) on the homepage

#297cbb on all the rest of the pages

**Comment by katebron** [comment]
are you sure about this? i'll have to change the colors for the menu, search, icons, etc when not home. Doable but i just want to double check.
<img width="1206" alt="screen shot 2017-03-04 at 11 35 12 am" src="https://cloud.githubusercontent.com/assets/1986369/23580384/c1d271ce-00ce-11e7-990e-e1202c269f67.png">

**Comment by hklish01** [comment]
No, just the bar behind information and news - not the whole header.

**Comment by hklish01** [comment]
I'm still seeing the title bar on the non-homepage pages in a different color blue than #297cbb.

**Comment by katebron** [comment]
Clear ya cache
