### ISSUE TITLE
Remove inline styles and add to stylesheet

### ISSUE THREAD

**Issue by hklish01** [katebron/notthischarter#14]
These are all the inline styles that I have set. Do you want to add them to the stylesheet and I'll take them out of inline?

##changes page title colors
##except for homepage
.page-id-558 h1.page-title {
	color: #297CBB;
}

h2.query-title a{ 
    font-size: 24px;
    line-height: 1.15em;
font-weight: bold;}

.post-content a {
    font-size: 1em;
}

.query-john-stasik-block .query-field-post_title {
	font-size: 18px;
	font-weight: bold;
}

.query-john-stasik-block .john-stasik-status {
	font-size: 12px;
font-weight: normal;
}

a {color: #297CBB;}  
a:hover {color: #297CBB;
text-decoration: underline;}

#masthead {background: #dbe6ec;}

**Comment by katebron** [comment]
ok i transferred those styles to the theme. not closing this in case you need to double check our take out the inline styles if you haven't already

**Comment by hklish01** [comment]
I don't see this change:  #masthead {background: #dbe6ec;}

and either this isn't working 

h2.query-title a{
font-size: 24px;
line-height: 1.15em;
font-weight: bold;}

or it's too big.  This is the style for the core issue headers on the homepage.

**Comment by hklish01** [comment]
Ok, I cleared my cache . . . . and I see it all now.  Everything looks good so I'll close this.
