### ISSUE TITLE
SVGs

### ISSUE THREAD

**Issue by katebron** [katebron/notthischarter#3]
Heather - put them in
Kate - style

**Comment by katebron** [comment]
Also need social media icons near the search box

**Comment by katebron** [comment]
I added the SVGs to the front page. Haven't closed this issue b/c:

- is placement OK?

- should i get those icons in the header of the pages each of those link to?

**Comment by hklish01** [comment]
Interesting.  I'm not seeing them on Chrome on the Mac.   I also don't see them on my phone but maybe they're not there at that size.

Only put the icons on the home page.  I think that's fine.



Heather Klish | Systems Librarian
TTS : Library Technology Services
Tufts University
heather.klish@tufts.edu
617.627.5853


-------- Original message --------
