### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by hklish01** [katebron/notthischarter#7]
Facebook:  https://www.facebook.com/NotThisCharter/

Twitter: #notthischarter

**Comment by hklish01** [comment]
Maybe I'll create a block that I'll place in the footer or in the header.

**Comment by katebron** [comment]
Don't worry about the social media icons - i think they will be somewhat easy to put in the header by the search box - it's through the template file anyway

**Comment by hklish01** [comment]
Sounds good.  Thanks.

**Comment by hklish01** [comment]
Hold off on putting these anywhere.  I just asked them how often they're going to be using twitter.  Instead of embedding the feed, I might just add a content block to the sidebar that has the social media icons so that people can link to their pages.

**Comment by hklish01** [comment]
They decided they want to social media icons near to the left of the search bar.

**Comment by katebron** [comment]
Can you remind me which icons besides twitter they want?

**Comment by hklish01** [comment]
Instagram and Facebook. The url are in the issue.  Insta is just notthischarter



Heather Klish | Systems Librarian
TTS : Library Technology Services
Tufts University
heather.klish@tufts.edu
617.627.5853


-------- Original message --------

**Comment by katebron** [comment]
social media icons are up - styling could be wonky until your cache clears. when it looks normal, let me know if you want me to keep the fill the same color blue as the links/headers or if you'd rather have another color

**Comment by hklish01** [comment]
Ha! The icons are huuuge on mobile!



Heather Klish | Systems Librarian
TTS : Library Technology Services
Tufts University
heather.klish@tufts.edu
617.627.5853


-------- Original message --------

**Comment by katebron** [comment]
can you clear your cache or try a different browser? not seeing this on my iphone

**Comment by hklish01** [comment]
Cleared my cache.  It's all set.  I think the fill color is fine.
