### ISSUE TITLE
background

### ISSUE THREAD

**Issue by hklish01** [katebron/notthischarter#9]
Can we change the background back to white.  i think I like it better.

**Comment by katebron** [comment]
which background do you mean? body or the sidebar boxes?

**Comment by hklish01** [comment]
Body



Heather Klish | Systems Librarian
TTS : Library Technology Services
Tufts University
heather.klish@tufts.edu
617.627.5853


-------- Original message --------

**Comment by katebron** [comment]
What to do with the boxes, then? 
<img width="808" alt="screen shot 2017-02-26 at 9 45 38 am" src="https://cloud.githubusercontent.com/assets/1986369/23340681/80226286-fc08-11e6-955c-79ffe501488a.png">

**Comment by hklish01** [comment]
Do you think they look bad like that?  What about adding a light grey border around the white part of the box?  Just throwing out ideas

I just think the page looks fresher with the white.


-------- Original message --------

**Comment by katebron** [comment]
Yes, i do think the boxes look weird without a different color background. To  me it looks like the CSS hasn't loaded completely. 

Can we go back to the original #eee gray background and try new strategy for the side bar content?

**Comment by katebron** [comment]
ps. i tried the border. it's ok but i think it looks better with color contrast

**Comment by hklish01** [comment]
I really like the white better.

What about adding a background color to the core issues?



Heather Klish | Systems Librarian
TTS : Library Technology Services
Tufts University
heather.klish@tufts.edu
617.627.5853


-------- Original message --------

**Comment by katebron** [comment]
yes i can try that

**Comment by katebron** [comment]
also - what do you think of the idea of having a different color on the header?

**Comment by hklish01** [comment]
Sure, that's fine.



Heather Klish | Systems Librarian
TTS : Library Technology Services
Tufts University
heather.klish@tufts.edu
617.627.5853


-------- Original message --------

**Comment by hklish01** [comment]
Let's close this.
